version: '3'
services:
  app-mock:
    labels:
      purpose: personal
    image: rodolpheche/wiremock:2.28.0
    command: --global-response-templating
    container_name: app-mock
    ports:
      - "9100:8080"
    volumes:
      - ./wiremock:/home/wiremock